name: Run tests

on:
  push:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First number'
        required: true
      num2:
        description: 'Second number'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check for numbers.txt
      id: check_numbers_txt
      run: |
        if [ -f src/numbers.txt ]; then
          echo "::set-output name=numbers_file_exists::true"
        else
          echo "::set-output name=numbers_file_exists::false"
        fi

    - name: Create numbers.txt from manual input
      if: steps.check_numbers_txt.outputs.numbers_file_exists == 'false'
      run: |
        echo "${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }}" > src/numbers.txt

    - name: Run tests
      run: |
        python src/test.py --file src/numbers.txt
