name: Run tests

on:
  push:
  workflow_dispatch:
    inputs:
      graph_string:
        description: 'Graph string in the format: source->target;source2->target2'
        required: true
        default: 'A->B;A->C;B->D;C->D'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create graph data file from manual input
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "${{ github.event.inputs.graph_string }}" > src/graph_data.txt

    - name: Run tests
      run: |
        set -e
        python src/test_graph.py --file src/graph_data.txt
